### ISSUE TITLE
Challenge timeline and scope

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/tomo_challenge#11]
Hi everyone, can we write somewhere a challenge timeline? 

In particular, I'm wondering if we want time to try to promote the challenge further? To get more people interested, and if we have time to try to include specz incompleteness, even a simple model.

Also, there might be enough material to turn some of this into a small paper if we find clever ways to bin (or rather split) the dataset. I mean... this is a paper: https://arxiv.org/pdf/1901.06495.pdf

**Comment by joezuntz** [comment]
The challenge is now slated to finish at the end of July.  This is in the readme.
