### ISSUE TITLE
Something weird is going on with i-band SNR

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/tomo_challenge#8]
Grabbing the data with the `load_data` function from `challenge.py` on the riz training sample, here is the histogram of redshift I get:
![image](https://user-images.githubusercontent.com/861591/81816782-1adcd080-952c-11ea-833e-af111ef1d000.png)

Looking more into it, it looks like the cut on SNR is doing something crazy:
![image](https://user-images.githubusercontent.com/861591/81816877-3942cc00-952c-11ea-84d0-8623d3f596ea.png)
the yellow is after the cut
The formula for computing the SNR looks ok to me, so I can only assume maybe the columns are not what we think they are in the data file?

maybe magerr are not magerr?

**Comment by EiffL** [comment]
hummmm suspicious looking plot of i band mag vs magerr:
![image](https://user-images.githubusercontent.com/861591/81817405-f503fb80-952c-11ea-966e-0be2da779692.png)
yeah idk what's going on

**Comment by EiffL** [comment]
Thoughts on this @joezuntz ?

**Comment by EiffL** [comment]
We seem to only have high redshift galaxies that pass the cut....

**Comment by joezuntz** [comment]
In the new version of the ugrizy files I get this in the HDF5:

![download-4](https://user-images.githubusercontent.com/220537/83885023-b2090280-a73d-11ea-9de6-792016bd34da.png)

**Comment by joezuntz** [comment]
And i mag hist looks like this - seems fine in this version I think?

![Figure_1](https://user-images.githubusercontent.com/220537/83885577-71f64f80-a73e-11ea-9303-7839eca2fe55.png)

**Comment by joezuntz** [comment]
This is `ugrizy` branch

**Comment by EiffL** [comment]
Ok great :-) So #12 fixes this issue

**Comment by joezuntz** [comment]
could you review that branch and see if things look okay?  then can merge

**Comment by joezuntz** [comment]
added you

**Comment by EiffL** [comment]
Ok, I'm gonna close that for now
